# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'MGAssociationMenuView-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'SnapKit'

  # Pods for MGAssociationMenuView-Demo

  target 'MGAssociationMenuView-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MGAssociationMenuView-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
